language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
jobs:
  include:
  - stage: Test Frontend Locally
    script: yarn; yarn test
  - stage: Deploy frontend to s3
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      deployment."; travis_terminate 0; fi
    script: yarn; yarn build
    deploy:
      provider: s3
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      bucket: "$S3_BUCKET"
      skip_cleanup: true
      local_dir: build
      acl: public_read
      on:
        all_branches: true
env:
  global:
  - secure: dACKpOguTmUkotpztSUlf4cYuq3EM9G6PkfMJN8Pcl8ByGKDy6XAwqQIW/2YuNLJp1Gg2x1j8XGzm6FmJ3FJr/SGvwzx6hIqubRWKVUZwqb8mzStDgn+A7VAx9sQf/+bc9rQSSt2nVHCUs08o0NUA9a4GtO4tcIH5Pnc2VC6daQu8zeA4dkDyD/4M0CJ4VmCL9CIp3jy8oIHSZbsWtVBXyraHT9Cj1J0P2SMkSIj2991cS+hnz+fGP+zMOHHiEhRforGX0yMpZC8ThX9NNFVHdgElllJZXq2HZh/m09b/jiY2ChbZute5F5f9wRzY/ZAwFAvsq4qW5M/MoUOgSd+uwVHcpEkK+m/2I96QuV2qWqHxBCgjDDFqCUhqHXWMNGsy/fPUFv93VHy0PDraY+E44QuMa+CRfb9dJLMvmtdTuTUho+xl9QhLh83EYraLT2qYlZiWCHS1ye0e9+8igD7yPqgI/0Ru8/i63qVWt1BlI2DPe15A6aVrBfNBUCCzbcShkHmRWJWe/8M/6D+dvIOAwEfo+07Q95MWYrhhoL0Go4SvLaOYIpq5HE9fAn6n3/VVkO81kerZWxu0ZmqhYwwhvn7kkA3XfjI45kGBsTT2g8wjifkrYgzU6r1d1b0o7XtWfd7wG/mLkDVw/qp9zcTcbE5VUAxATLhKYvnalZULE0=
  - secure: oROTF7HHBuhZ7rt5wPAD9mzZX1Uydg4GF/Cmwo+3XU1ScTGK3O86gz/SlZz2onovVk128FsP1wknJTZ6PmZagaSMjdmAwQlrLlQBEF98gwVTo5vtOExGe32aJqeqyKfBFGPL08Gl8Y8YHkzoXbL1gJK4nUvKk7+dCPVGxsacgOsxAXKqlpCRSFNpCzYSgWgvhil9afIV7VVdjGKOYieVeeNWHHPquiJxH5CC52BRW8GfcNwLzKvXGzXqkNqfFcS0xtbICgl2KNzQOnOQ7XLE/E8tTqZSje/TX3Ulvjzol/HYzaQ3SEVsH2Ihzs9STM+3wuj27pG/ZrUkP1eqU9KDSiBXJipOIf7FdCid/XYcrD4zYCZ9WmK1utISc3BggYpI1EwNiJhxbdhbs5by8MFI4tn8q+By1YGqMxEW3V7ZkKYXN9hPX5q6xcO83rADE89pCstOipVcSFZv29/7Fh8nY2+OM2EKAECokn4RPBf2+ePvZb55ma9ZCOBjfj1CYV2PGG0AXzxyFlgrCB48doil8PUZBuez9n+RFaKztzjr88p++oL+hV9d8R6G0Fbs6ZJsxHPFa7DdMvncNUI4ojNhu6AyszOkBbYOCZ3ZX++PAauNLH26AMkcJnwj0KK24kMe19eb/CmsDte0QIGnBAVMbP2CGaVaaJPPLlFFyTaimic=
  - CURRENT_FLOODS_BRANCH_NAME=split-out-backend
  - S3_BUCKET=ctxfloods-frontend-split-out-backend
