language: node_js
node_js:
- 8
before_script: yarn;
script: yarn test;
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET"
  skip_cleanup: true
  local_dir: build
  acl: public_read
  script: yarn build;
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
