language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
jobs:
  include:
  - stage: Test Backend Locally
    before_script: cd backend; yarn; yarn init-local-db; yarn local-drop-rebuild;
    script: cd backend; yarn postgraphql-local & yarn test
  - stage: Test Frontend Locally
    before_script: cd backend; yarn; yarn init-local-db; yarn local-drop-rebuild;
    script: cd backend; yarn postgraphql-local & cd ../frontend; yarn; yarn get-schema;
      yarn test
  - stage: Deploy Backend to AWS
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      deployment."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: cd backend; yarn; yarn rebuild-and-deploy
  - stage: Test backend against AWS endpoint
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      tests."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: cd backend; yarn; yarn test-on-aws
    after_script: cd backend; yarn; yarn rebuild-and-deploy-with-tons-of-crossings
  - stage: Deploy frontend to s3
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      deployment."; travis_terminate 0; fi
    script: cd frontend; yarn; yarn build
    deploy:
      provider: s3
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      bucket: "$S3_BUCKET"
      skip_cleanup: true
      local_dir: build
      acl: public_read
      on:
        all_branches: true
env:
  global:
  - secure: sQDKfvfUbzrv9+b5yxah4lWq/IuoDtllSK5K0uRt7heUZqbUp4LIY3AkCxmhsXHgmrpbRgG/igjiozKHAxb/zhoXJIUMln04+/cEOuyUIegQEQwQPZWRJnzb8kxIy667Of5OH+xlFdGOkiT7cn6WpIOaNR8lyAmY+plE9sPvNsczRBC/kXn/h/xpyTqSGNMRUMsWKzdgdNifrffWS8b4DzhLOUcJPacKvAv1q/hUAbEXRQbGOYZdBjZ4LchkLGYs00rXFGB8ByE1xwVOviNQwKKgWe/Vpqqe8Xzf1o97KjLR6zTCcWTnOVWAc0T1S265TKR3RksLdiX+xQ/BaAaK/ibRa4nAxtlw9Yk8019M4OO2z/r2CcDudmKMhhWFqbMjVVP1LiDWV4COAa0wPR7P29mdTMu2J1hTBpWRdHjZnbp8DH1kWyk5IAS/2RZSMZpmwAmfDEdWcnV9YFZq7Nf9/gwatg8AT+RibQnKh9qlWXGdqHgtpb8VuDSDIelFjLb3Cao99vNV0xVqvjHy5tRAVUrzjQUpfNR7oLjLl9tuq5NEfd3mWMW5JwwxqK6bn87vBP7kSq33Muq4QFrmXp6OfVqyXTd4kFRHzT9zuE7K5kEjghyxyO5YNj5oWd+CoRcAujd8XlPz5fO5xg5aqDSsCmY3Ed4lXRJDxiEmP1ebME8=
  - secure: jb0TCA/LS2PdAKr1JZX3V6whqZ8OJXA6KY8yv6LZaDmljugXJQCyOeRRcAWwlvq1z92cAdCrKnpfxeSwgcSs4xu+qx7bz7tgPHTe5AXGlR0v0Y+oNKGXBreyUA1jcOVtDbHRvaWTo5N0J3nfyJg+9yBC/SR6uhEJM2NJDr9pmy+lg0WP0PMVcElbZ20rCNryShodVx13PpdlBbiRTg5gYcJ9zmaBZnoqFB54WSTQvET6psa4+HEFFGKC5p9gKc97AtWX4dcnB3tjvoNbWw9mXdp41ivc49ahiRpH0uueq0LPor+5uTAaj2dQYA8Brx8YP4cbsPgKnpxqeXmbEOVxajDSx5muroQ23prE0Vaw2z58PFFuouGqyff42Kp+vUXxsKbp3cu+3acj3QuQvrbuDLqO5mOBxYT3BrvRBRCtEDBShm2nTW1AlsGWs/gTugN80qDm769y+nn2OKbnWCLUXZRG2MZD6IhwhhkxeJTkHqIiuN8Zo4BYs5MwZrNfIGknu0180XoffDcE6Qp+7CPPX5pX8H7hH2vgP6UtlmrzGtmo3LthFTxiIe7qP5VHOcAiXoJcKtQx/by7W3DhaDcmSoXcluYXqSY2PEL3500JcSCV8e5xoHR8xsmilLt0ILHzrcgr9wa+3pWNu2PKLtkmu3ewSdPnPCSBGzVn7p0UElc=
  - secure: RluLAZB7d04V6/nAmazOKJ5eWoK1JsYW5JdOjw0IyAujVCqv3rgM1qF2y6Tii5daRZvj/FHQumxqTPvOh5aD2uIbCSraXd4C6fd/MaXPoY7IKRUyAgPlqxM+aqbBjVbFbzhG0bZJEGWvO29qmxBWuQbpi5oS2U0rBeHaVrBcJiNGWjT5Bq37V69cUxYxnYcQlwxmf5gDB+eajvzrucmvuLY2x10TUAZNuR1Ifb2/RJgz4EILzZrHaTG/KY5W6U+eKghBuPX/kpTZkhQ1JuVmftNgAS51xJ5H5KIRk7l+CDFc+bCBJIzj5sf3LXLj13WqJJ9CZdmLUKyuAmNzIGedDt3o+VJeoaEsLJswzWBLOUSyu1eglxH5ABvsZOl7VgFlgRQOb0TjRhFnlzlT4HKQEPVf/QtBNJFeB7O1ved2MG+hznuJue4S1lALTmk9s+0PHjf1ctKWTwboildm/SfoocAka11IXJ3XzebgO/N0CJW8TrRGl33r1JlpR1/gpNYVtWek7JVRDHm8FpIqn5L3yNN/+urq1KVg3uptrofj55J51PvMdxv18uRKzOYk4yoQnf+W9uvogJfR9025VzLzAKG4/73j5qZbFzG6tbmtjtY/Q4WIJTsWVXG578jr/5MykVLt29AVKiEh6doA6HGVgXiPi5a662bDtk8c+lXhTAk=
  - secure: vm+Wb+vd9sD1k2Wr+deUuo87OttXh8TvpRwF3T6JM5p0dkOlnVrk8A6B5kqwC/Az6n1tTO34rrAA7icbxUOGTjBQ7qywtMoXZlOTCii8/N4GmdOjL4gEfuP9pnKwWNQfxat+dBsKpm4zNvo5vRRhoajbVGmgtyyum/JYI9Q9T0VWUFtEYnaaIymxf2z4PZncTHS0gpx9igfEZFBkglnd5cZjsiNKs+1BgKP1vBEkbnLRPBF43CfJAlHZqKdQ3Mz3NDjlqnkTc79I4ZBdvPC6Xc7ixVy4wG4kben1TDNbto+ZSmEZoro3XPnObDK/Op4tcgj4u3o/9BN+tOj/JZNNWvKXnTzDhD/0DUGAs9QZNbwPQa43hw6tskKaU8P5FOG1M7fsejpqUIz/hhswMhMVlChH54da+Jy/3T00rvXqFoK1GM+OoYmiCl6gk2b0dylU3eIz8rigbnmejJLbQhT/AMKdIeE9PvZ8RcJOY1BE0EIq2Gd/Kgszzxs16TTMHRW8cAPa6KDGr2d3hMEEHUNiyjtGrEfc1Km/wPiDpphBeRgdhqNO/H0M1F1bqg1jvYwnF2lvWqQAF8UBbF3uashhwXB8NI69/1MBjXt6SEstM93cRo2U/uTX7Nr/9t+PDAOSxx5MQLC6f5vFxj1QXeR/whOdZ8sI1GSGlf6Nbovo6Bc=
  - secure: c0eavD25IXLl+Q7HLjKq7S3CCGaNHGHwdwv1l3wWAkMODzjuIGjkzEKHEBqxnKaHYv9YgmxBLD/ChOLlLA6Z6W4B3ONYshOPe+45nZwXC/cXDCL2QIzDL6odIdgRsjldF+IE067nLw+i0wH0bZmqFAMvOMBM/KuO2KVW+lbIVmN4edroyDaDFQPJezQIqRghqZFr5TYUpeEX7zjLH+RNTYLNoyziwFD+Tr9e2n7QO4CScqrkR3bafsVl5BtRXC9e36fM4juGdPvOgDMqEJyHcBMbV2fKSndov/rbaB1WhTV9V3GrrR379JQEumKqthVrMY4azJYAJYgi0gci/HMnA3TiXFaXuH+ocNyFb3phi48F2hrm7Y3T4zGnfjcRc7Df6bS9CksjErfWgRlUQXb0fj/hf37KZuHfYXZWRSsJy4ke6nUjFKV6pb690r3fN/kXIn47rT3xEH83jkdQNTngAk6oFC7rw/aLprxJNczybQqto+A+GPaj47LPL68xwbipyy7VfnhX5CvpB6HNWwvwfQv998YA0arIRSYp8rZDQLbWZBb93tnd25jbf4EE1nMndQ8NnpoJgi1bMtXRAZt/oMgehst40KojF4BiNOwtrO1afy7zOaJB1btoQLB2Xh/TyoIIAFIVEzy+lEaYW8QxbVQJ42xQ3BmRLRSPGIl2hOI=
  - secure: W4UzKr3O9XuhwTLb8Z7O5BdvPIh4LmLhwR/U/h25ij7IrbtZuxJvYkyD8EiqlJfJ19zEX2yRr1SsG6m8P1JYDTjnFSyxdMjQCiyRPzNoe094NyAhHbtKbJnzrm4E1hxMov9wWaHY+0Ga5zjFNsjlL+B/s9EyCE+oTQEnWljO7wQoUUiMH7dlF9UAInmXJBLTyOAKJKhm2c9uzceRswbI/1eMWNu7G3ja1+0gfiQyw2aFuCyQziKJfIsx9xdQhX/zv9PGjBtR9FO15ppxY1cAf0nBPbZNrBomg9hOHg+uioV9bUKKlJur2ttzSypn2wsw1q3KHe5Z+STMQKFNx0yfj1HzLfrrcqdkBeqwpX1TO0bQJPKF+00pRyyZ/gZUYXclr7BMEetH+NmvZDGABGvnv2X3iexyn00jxZ7A7MkO5i5YlXqSVKiXZyHOR7nw2H80R24/USwvJH1NCMn8Sn4Q+xyjecsXc9PPbGkNZyAijM/csXVQ7uBHTs8v9SDXh6d4Z8VZ5Ja5/wZa9jK784N2hdDKwfuy2Hd8CJ+phbhGuvhB2Ge8hfin6riSAd6sZZ+j74MChxtnb/cnkjyVLlYd83t5M2PNwETZKFIDXobA80mRmRHDslMbfJOdNvn/uRM6BFTha47GMI7LER82xqDXYJOIyA/UJYGbNy94Ju/wFaY=
  - secure: DpQ4TGPMmG541zYBaibok/8KAka0HiyYROqKGfW7GD2vNZqA22BgL/A2AHOU3wfZj9kcW9Lvn3U4uzNAHV1T1PLoOXvNretkqvPMjhJVS4LuqnbBpXAZfjHsK9vuAQ/5xxhmMnlOaXiE3L+ofLvuX0MXD7C3wHoja+QLk4fPCd+fcZvdtsBXIFFjbyzplYqSPx/QIA9qt+qCBze+ijyMKBpiVHieA573EoV6BSaGwavVplRR2SPziaQT5INt5RvS7lc1ZMviaWGOxIeRFx11ZqFP4ZalHXuSCmlhadlELb+jM1HJNhc+gGCEYPWM4s4zozytg3l/1rNFIxRZikxgaGz0NH7tlmdtLrmgaVYyXM3OBcY9wyxqZZr5EcJR6+np+KSCqGzTrj+Y6h/NBaxrPSD6iE+JX423iCka56heDIaYbPvORrhI7IQaiT+lg7UGOz1vDb4Ujk58xE+j70IUALGGchJ4uJ9lMDtSvSrXghF94otJlmG8dUbO3XFuUYDj6Q/aVuKkgrr/LvHvNhoQ8mO3EHGUg+BmHP31WlrAXMyWAZtoFyrNV2b3uzTIpYdBTa39k8/VvsHL4cpF8QSKJGPr+CdaNnbaancqYT/CGLjMWG+uPzrbgxH6G9dAhkqrg1zA90cqeUYzkNLBYt9Hp79yUuQfReqL0mbm20tayMU=
  - CURRENT_FLOODS_BRANCH_NAME=master
  - S3_BUCKET=ctxfloods-frontend-master
