language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
jobs:
  include:
  - stage: Test Backend Locally
    before_script: cd backend; yarn; yarn init-local-db; yarn local-drop-rebuild;
    script: cd backend; yarn postgraphql-local & yarn test
  - stage: Test Frontend Locally
    before_script: cd backend; yarn; yarn init-local-db; yarn local-drop-rebuild;
    script: cd backend; yarn postgraphql-local & cd ../frontend; yarn; yarn get-schema;
      yarn test
  - stage: Deploy Backend to AWS
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      deployment."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: cd backend; yarn; yarn rebuild-and-deploy
  - stage: Test backend against AWS endpoint
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      tests."; travis_terminate 0; else npm install -g serverless@1.25.0; fi
    script: cd backend; yarn; yarn test-on-aws
    after_script: cd backend; yarn; yarn rebuild-and-deploy-with-tons-of-crossings
  - stage: Deploy frontend to s3
    before_script:
    - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS Credentials not set. Skipping
      deployment."; travis_terminate 0; fi
    script: cd frontend; yarn; yarn build
    deploy:
      provider: s3
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      bucket: "$S3_BUCKET"
      skip_cleanup: true
      local_dir: build
      acl: public_read
      on:
        all_branches: true
env:
  global:
  - secure: Pa3TgL853Ch04hgmGjCOp9nGLqtapDNX9nXDaWeUzMdGIEZGpE5frvfrNVzT0hLgAayiJ02HayG9yRBdWD+OS6+nOZ7wAlUVgD65IiHaD1Rl5Pu8vye111TmTv1TgDtx4P77N2tYunifxBPOxgh1Q4zWeXxJi/2XOD4y5bxUm+qbEiIzqg5b9OVKaDxpyxJIn6cEC+Y+FkOQ9AdJc8D3q/uMGUvYlX7XgLhw6Dyfv6u+rtJseAE+jHVi1ev3OusZ9+hUNClnxkcuuK4knwGmASO2ASJlOv2XcgC/FvpIHz/5NijuI9ZhoGvFY0j8rl0txD2PXuugzucy6jbzjSJDNtPRlHsBe/DwoEAD6SqwEBfYaCKkSStJprcIIV2Q8j191HX760hmleH97AWW/bhSrEeael4ouJlPUWvCzJOk7dYC7BO8gAAYWvy+kNfOS6w9COS7296/P2vwjkFEjtM1YQeHIP+KQv11mFEF2s9z4+N8n4LJxIETCM3khsL2A9I7xjGgnmA7wnX1g3uWpraKPHn5Tuo7Vrs4+w353Af6+twdbEh/ZcUqMfXVlq4jzyJWtBE5CrClo5zM9S0qjJ9gUlr9G3+tCeGiCvAv9EBlc8rBlA7HR/cAS3w/8r1nysbgAWQyhmodRXpAjagaf6QVEEcHwGkJNX/RO9IhSpXITOg=
  - secure: YJRBoxA7QoVQWSRuNMXAJxYczKWT0tvuMK6ahcxyjvWLUvb34Ana7EiEpLZOtFmQWEam0JMD6yPch+mI+4VBnw7n0b64buVny/1gBF/SgbK9hJHspf7D0r/jMDTVdLBpkzruqALLJjBHQGYwCtvq/AloGUKwGbsdH6W4mLInuUVcK34erezWZ/OD079jazv6iiRForTEe8TqyYYOUCddOrWvhhzkjOg9BZJhu9G15ykHIgLjVreRTqEUd055zICsjcTRraYYEMhdQqdaeQ6QIY3JTfiAHm6z6KokAbdOPbwqnquGL4hiG5Kq4tkAfQejCvN4ITVJvMNyEYq/qvI+x+a6CCzuziF4VNbcgBmi/8c25+Imog8z83TOtjOGhuv3ds2f9+PmdT8BxvbaNdWm9wQ/R0TNm3vK/22JJVnGYdO/81bKngpGm+Y6RfbgaZK11cmWGARqPKg2/H/TpZO5rIikycjIUMTUI+Q1+uSKOSptIGJ6j06pQwNnImBvHIro0D34CiKKWZ0o41EqGO1R7INQ/iLfKrXJi54r2e7/GkzopWEh+kXowyZVlxe/dGcCpxdBPwKMetlxmDXAgievOKgjHDTPRS4pU4mZKKXx63LcIK3HeB7zjx/pHgaxVzZXrV72+R8A3y2on5stSHmHgAdpJ9UQyKpopUr8wzBlJPQ=
  - secure: PJnbqDpH94JwXKnL6QU57+Y+mqXIOKYniG+ImhgDXbGQsy9R56LQVquLMqEuvh+UnMTHPdYP14W7uWXNFz0AOP/twZT0FxthNAHhQ2HBq/IstZZj5yD1UVCn15NJSqW7xceyB+bLUepb/abJzQ1AgVO/HNWof3zFn6VYQP/NUQ9IcuyGAlYaqli2n79iQiUuynaxN4ecos1Yk0l2RQmVy8ig5tD8ua+83y4W0mpI/EQqpj0VXNzloolLH51vgC8umDD6zoIWgIULXq14n5xvNnFAbcFPpltSPokhkF/waDaKRHTFoyZECwfP26X5nGTq5qTEOZZtumwx/bVwJQYNhR9fHx0OrOh+H6HEp8rNojHwbRrjNyLg5ZXYqd025X/ckeEHK4GSdaMG15AeQjuyzEpaPpCDtPYG5L7EAX0tFgqsa7cicxh0wUok2gF1jYYF3R+532S9Utc4MbNv7xXd/m/Fp/eoBiXfgoc3UNtvaQC9CD8FwVwT2DZYC8NSOFGhU89nWym88yKTjuhcp/hPwMm3+7cLYptuaHWvQI2p34mBF6FaSpKf2K0ayo1akTBf1Nbu3HfRrhhav0JFt7cSQBFne8PFL+gfO7/7ISOYE6pNKoxw414kAFGgjp3C0L8COQtxhrBkiGufef8Mx9DD73rFIStpOLaB4F1sq1A9zsE=
  - secure: kws00DQ9+i03Gfj9Mu7ZMOysxv2dxrqE3zvbQAnToeg8TVWnN8yzKprPmnLgetSxGRapbYAQLcvO802WmKHnxRlgpfC17qYG6aBpEireycPA1zyYiTPlAKl/IBlNOkDhTFEBkNX8UQT1eoY9gnWXvYNiN7BeKUhHviOk2NqRRTmSXH1V2KEhRXfSa7Q/W63F029fQXfUxu1VJdSkp96l3FwQbjufI2wL0NRusTAPIL5DXHrjmUaH5Mr06nlBAuNEA4saiklO4SP50Pytsp1MmklBn0CAjblzQ+6F+au95xnFGLxJsJS1butAQvi3tmtQi9sUD5VzhnEb0dPJGrKBRcg5/W9s536UET5Hq/4TWilIxJpHjTIzKAlDCoh3KguPeqJlXNAdDBEnwf+30Aa69WeM9k7klKQFXxGavWq0ybQtj7xvOm9ahgNTePOkSlsc2YIcXgzztE85Mv/7pOUL78o1eqvdO2BgIOII+ZbX/Z5rSPVDqf/qsCpY/rjwcpDXBaMzCJjcv6Yd3DHwbHvLta5hHnFvII3GFeQncm4boq9fubI3HMRSIY06qCb60jHKxKpfiWaipwatwl4jTrgYoT/9XH/Rs6/geqvYEEn3khvexxJ6oJWBCd2cvoSw1IeTNMchSpOCkYpMxJOjuW4HS4UQ+aWeRcYgq2cbFg9esMk=
  - secure: mrtPbjRHyM7xSYd1tth1IIgh8Ur4QRJQMU8L8TtpBoO9Em5ht440WvxGOnsr5EYORnWZgttPALG3MEPLa1W8CHBCFnuNNtAzTi9fvlCJ2XmklLyCEnpsL53X58nNkRllA7LkMOsnYvc5xkFqBrMHNKeoRTTHWgl1QE/f7D4Vip28JGAjbiM9vvSAAZTY0PoXVFVDNkPt0Y8UW3mlbl5N4Lv7PfBIZnQWuDWGPIxI2JUaE3v4Gs3SpzA6csFz9x1p5w8FP34XY8B2xNRbiF5qTnNybgobDFZBrXYvS/NuOn04S5NX0FEtfdEKx9FxTtjoLxAbVOxyaUYw2TRhYVNAS0ozE5X14Hgcz6dZ6sYf9fnxXGKZweQfgHtft5nmxa2n9dDt9El+Vy1oJDIfPQE1HniSNOvywUbeJq0oY2a9A+XGQMC+pqdJlVKP+DNU78+Fbn68qeso6wOQckuWHR1SemzqUv9LpQNuAN7Xh6oep9cb3wtl/4cDse8/onqk4iomK2Lp3pVb1CAMD8LBdrWGFe/2Io3DZRLDfwb7P1vbHOHhgaVnEg3Wc8MhHfuLTRU6Oex8zNb+1P5AD7JwoXwosFdy8dSzlm5rsWqoJrC4BVAQVP7W1cKPgweAklmR8eYF1pAg7TIhmMOpIDaKBYrREjQBjyIqc4sbMyhoXYTf1rg=
  - secure: l4vmKP1GU+BLE+ypGbo5BHUujFUPKMJ5sLE43Asu99ktuoOMOvAf1lNg7g0irG2q4u6qju6TSQ7P4Bi2EuAZrOMMXlzGE5diPf9NUd9HNAfG+SuYn6L5m/FXttEGhRqRQ9EJxvgiemcJX5f+x4jDJWvQ4DHV3RkvYOMN1xjk+RikWEv+3pI/MsSkb/rCjnm0h4Y1rEBzKron4JhNI1d1DsEJOdPmMhmVvHDAn1AOG7s98i381g3PkwlPcx6rZJOmR45dZ0okg0oU7NpoIhO6ZlA+6QwbIKj0q1yXL4xj86ipWnzTMkVyLh6diL6TlidJohkPOBFXWAadhkEqYRMb1wVIO6yfKSroofdRphptRI1EaFzw6LodNHY0p1qSPN1yTGu25xr5CTxGogls9QCJ3luTFVDDJlEUDQXkNV0wzMhE2aYwmJHSJ/53s0lZeOgx0TBieo4CD5+SX3+hmckEoy8vDQnfUCwJmiky44VkqGJkiOzsZE5ermsbY6EiT8FWNUTAIvS7J/L+6ZjZg4tnfw2n4f70z9yqVrCxRGa9XB8HjjaY+WU2xOCYqBdTU9NYa6+WfBlsute5w5lMZqxFZCXhhdttkt8U188ne+dUV3ZXGiigq1HiYhda0D0MV20bVkNdt98UG82A7KW1gz67jfX6lE81Ah6hAAoPSxrWKbs=
  - secure: oKupEqCcGutTbjObNzKkKNb7MMrEK7ITyBBSl/VSnvn096kxs4g376b7WQK4KrLHHgHtjw9/r0ddAWVvbqUjVEyocCRYkOtcKnlBT0DfH+4PW8AgRBZnpZZbkbc6Rm8t6lBohdrSJXgu4EllZvQGN+ATqAfPOBviO9C0i2ih4FrYjzSFVeNj3O9RyHvqNWn9JKh2qpY07Y2MNYQNYMZxqusI3cDv6djUwu15ttnqMluEgU3VKtpuvNVS626sgBgoQ5aekJXj1OTvm2Bn7VjfdB2MZpPU3T/GyNYvq8JzbZcpZU01E5l87+nHretIANUuQFW2l2idv/fLePZiZ3ZOoJmSaluCdoeCTGPQIV8vHUBwRMzihGdZk1E1Bn13tLRYrYzkVuwu/ZnLNPLPge7j/MzXVRuLo2E9cS5PJ4aXzTQBfME10DGuFj5osPuR2IGMe4zC+1x6y8uDrvMCmBBU3KrgGoE6rGjIO8V16tLFGDHzAxayjfmYSEsG5Hs78oukpJW36rt9jidirLOBtiqYf2woHQvUScVAZs/fcFB5TsPi5+vqgU/Yn9jRriX7kI3fS9SVuHysa6XBa6QqfmA+fcV8T7cNkjs5jKYFUIcW5xaqNaRds5DxBEi9EYJMRirFfbxCmoT44NR5SObQX2kbKCPypYQaVDHPHEJRJmhB+gg=
  - CURRENT_FLOODS_BRANCH_NAME=legacy-xml
  - S3_BUCKET=ctxfloods-frontend-legacy-xml
