language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
before_script: yarn;
script: yarn test && yarn build;
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET"
  skip_cleanup: true
  local_dir: build
  acl: public_read
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
env:
  global:
  - secure: C4WgXS7WkEEuhk3L2PD08+z/Bc6ok5jUjZV2fOIMQiXpI7xhl85hf6YA8Q2DM6lhCqX4osUV1FdImvWiajHst9cAwDjbnVek1TXbtj8D7hUhlo2RbE8yB2zelWxzTP772vuejLR7dF59HvQnyHxWb/M2cRXwmR0vKPh3l3n1B8Za/ReM/z2D547mSJOVNWrK7kkL/LXEn7YHDxfdPEJ4mVeuvkgiOWrl2JEXYzFbnMEDPQbM/JywXcpDTjDwge84/Eqi2Cjli1TLaU2X7KoTaMSaqQjCy572ciPGA0/djg5x+Ed98e9RFktoIKudPMPLi7aWfWqJUunSptA7V3IykarXDXVPiVUvGrdkEauZP4mSojZJoPgoDpOf96hNphPc9WcfcBkliSxl/RDPzhM7pMfYX1hk6MpifKHJCo0b64DyqUGOC/BaONwBJ0Ou7Ur0sRlqMsrmUIpugp8JuRw5LflcRMZQo9+TTao97hCSyNvmJnrUblUVFqZEe83XNpxu7PZ7CYyO+IwIBerE1RTPDGl/Yq8Pvt/SVUm+rAoFoIzOryJMz2O8SLyfNGYPN7kKpAxbapSmY9s+lkbYjx530SF6dfLUfnygOx7MPA38xk5b+UiFdXOevzqOdMSZuE+7yhe8WqMNot2x1lGyEPNrYfLUwO+4mp0UMVLb9SELZXE=
  - secure: VZe0M5C2zGzcky+7as/RMDFN/OSmWZsqpzjCC3c6woOPhVlcCaDVo5rQttAviC71y0BJqFuEfm5c2ITxC94z15zOK3ftjQ/34IxaVDLT/oxw+B2arpoiC3HMk1o3uFdQvo7m17Q4+XPDN+IbY/SgZjMlxWuxEP1TfD7R0ef+kTfhNRVAE/p+waDiMpx0qXEqVlWiw4QLz7UAzvoGMMk2eqvfaNyHLR+CPWzx9OQA8G4Cp1VhEDnVRyXIIMK50/nWobEFQHEMvFV8pXIbSYamoB2o02gI7Z/SMwc3ByffmMPzRc/+FvOeKb3TTOSaBcQ6c5hBdUhEpM1Zrss/GfyBIJBT0ynBsDTYOyJzgJzG4amQ3L/rMAWxx9Bsl//Fl0PkzVgC5JtyAo0v/t1G8uVs48MhOYyxoWCWHDQ/veW4EN708zBPL/Ev9eIL9D5G4Ycz6N61cZn9ecFL+D1pskxdNBHV0U41IYaGGtMeXZGIMklW4dg1p/ubIBb4JLBDqAgwp5Bnqck4Ns/+DysPGdM3NNxfuNwckBEXA58hlJN4YnDvPlyAeFt8I8/9MNjW1bBiIbnFGgjGV4KLBSlczeYD0wxlxyUTwUXAd3vhCsD+tJQFULkEGT3lUUErXNiAAhJQCkgGmGkHzVgYwp7OGMOSHPAvQAcf/HoLPEdTDqiHx2s=
  - CURRENT_FLOODS_BRANCH_NAME=split-out-backend
  - S3_BUCKET=ctxfloods-frontend-split-out-backend
  - REACT_APP_BACKEND_URL=https://2omhorg3mc.execute-api.us-east-1.amazonaws.com/dev
